micronaut:
  application:
    name: pricing-service
  server:
    port: 8085
booking:
  base-url: http://localhost:8086
catalogue:
  base-url: http://localhost:8087

---
endpoints:
  info:
    enabled: true
    sensitive: false
